# Site settings
title: Cong Anh Blog
email: your-email@example.com
description: >-
  A clean, minimalist blog focused on content and readability.
  Sharing thoughts on design, technology, and minimalism.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourdomain.com" # the base hostname & protocol
lang: en
timezone: Asia/Bangkok

# Author settings
author:
  name: Cong Anh
  bio: >-
    A writer and developer passionate about creating meaningful content 
    and beautiful digital experiences.
  avatar: /assets/images/avatar.jpg

# Social settings
github_username: conganh
twitter_username: yourusername
linkedin_username: yourusername

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  toc_levels: 1..3

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Collections
collections:
  pages:
    output: true
    permalink: /:name
  products:
    output: true
    permalink: /shop/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      author: Cong Anh
      image: /assets/images/default-post.jpg
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"

# Compression settings
sass:
  style: compressed
  sourcemap: never

# Performance settings
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]

# SEO settings
twitter:
  username: yourusername
  card: summary_large_image

social:
  name: Cong Anh
  links:
    - https://twitter.com/yourusername
    - https://github.com/darkcryoo
    - https://linkedin.com/in/yourusername

# Analytics and tracking
google_analytics: UA-XXXXXXXX-X
google_site_verification: your-verification-code

# Security headers
webmaster_verifications:
  google: your-verification-code
  bing: your-verification-code

# Cache settings
cache:
  type: memory
  max_age: 600

# 404 Page settings
page_not_found:
  title: Page Not Found
  description: The page you're looking for doesn't exist or has been moved.
  show_search: true
  show_recent_posts: true

# Custom filters
number_format: true
number_with_delimiter:
  delimiter: ","
  separator: "."
  precision: 0
  significant: false
  strip_insignificant_zeros: false
